import { MaterialPreset, GravityPreset } from '../types/physics';

export const MATERIAL_PRESETS: MaterialPreset[] = [
  {
    id: 'wood_wood',
    nameZh: '木塊在木板上 (Wood on Wood)',
    nameEn: 'Wood on Wood',
    muS: 0.50,
    muK: 0.35,
    descriptionZh: '常見經典教材組合，靜摩擦與動摩擦係數差距顯著。',
    descriptionEn: 'Classic textbook standard with a clear static-to-kinetic friction drop.',
    color: '#8b5a2b',
    blockColor: '#d4a373',
    surfacePattern: 'wood',
  },
  {
    id: 'rubber_concrete',
    nameZh: '橡膠在乾燥水泥上 (Rubber on Concrete)',
    nameEn: 'Rubber on Concrete',
    muS: 0.85,
    muK: 0.68,
    descriptionZh: '如汽車輪胎與路面，高抓地力與強摩擦。',
    descriptionEn: 'High traction like vehicle tires on asphalt/concrete.',
    color: '#4a4e69',
    blockColor: '#22223b',
    surfacePattern: 'rubber',
  },
  {
    id: 'ice_ice',
    nameZh: '冰塊在平滑冰面上 (Ice on Ice)',
    nameEn: 'Ice on Ice',
    muS: 0.10,
    muK: 0.03,
    descriptionZh: '極低摩擦，微小的推力即可打破靜摩擦進入高速滑行。',
    descriptionEn: 'Extremely slippery; minimal force breaks static friction.',
    color: '#90e0ef',
    blockColor: '#caf0f8',
    surfacePattern: 'ice',
  },
  {
    id: 'steel_steel',
    nameZh: '鋼塊在鋼軌上 (Steel on Steel, Dry)',
    nameEn: 'Steel on Steel',
    muS: 0.74,
    muK: 0.57,
    descriptionZh: '乾摩擦金屬表面，強原子微觀咬合。',
    descriptionEn: 'Dry metal contact with strong microscopic asperity adhesion.',
    color: '#6c757d',
    blockColor: '#adb5bd',
    surfacePattern: 'steel',
  },
  {
    id: 'teflon_steel',
    nameZh: '鐵氟龍在鋼面上 (Teflon on Steel)',
    nameEn: 'Teflon on Steel',
    muS: 0.04,
    muK: 0.04,
    descriptionZh: '特氟龍分子鏈光滑，μs 與 μk 幾乎完全相等，滑動極為順暢。',
    descriptionEn: 'Teflon polymers yield almost zero stick-slip difference.',
    color: '#e2e8f0',
    blockColor: '#f8fafc',
    surfacePattern: 'teflon',
  },
  {
    id: 'sandpaper_wood',
    nameZh: '砂紙在木板上 (Sandpaper on Wood)',
    nameEn: 'Sandpaper on Wood',
    muS: 0.95,
    muK: 0.80,
    descriptionZh: '強烈機械互鎖凹凸，需要極大的力才能啟動滑動。',
    descriptionEn: 'Severe mechanical interlocking; requires immense force to budge.',
    color: '#d4a373',
    blockColor: '#bc6c25',
    surfacePattern: 'sandpaper',
  },
  {
    id: 'custom',
    nameZh: '自訂係數 (Custom Surface)',
    nameEn: 'Custom Surface',
    muS: 0.60,
    muK: 0.40,
    descriptionZh: '由使用者自由調配靜摩擦係數與動摩擦係數。',
    descriptionEn: 'Customize your own static and kinetic coefficients.',
    color: '#3b82f6',
    blockColor: '#60a5fa',
    surfacePattern: 'custom',
  },
];

export const GRAVITY_PRESETS: GravityPreset[] = [
  { id: 'earth', nameZh: '地球表面 (Earth, 9.8 m/s²)', nameEn: 'Earth (9.8 m/s²)', g: 9.80 },
  { id: 'moon', nameZh: '月球表面 (Moon, 1.62 m/s²)', nameEn: 'Moon (1.62 m/s²)', g: 1.62 },
  { id: 'mars', nameZh: '火星表面 (Mars, 3.72 m/s²)', nameEn: 'Mars (3.72 m/s²)', g: 3.72 },
  { id: 'jupiter', nameZh: '木星重力 (Jupiter, 24.79 m/s²)', nameEn: 'Jupiter (24.79 m/s²)', g: 24.79 },
  { id: 'zero_g', nameZh: '無重力環境 (Zero-G, 0.0 m/s²)', nameEn: 'Zero-G (0.0 m/s²)', g: 0.00 },
];
